### ISSUE TITLE
Cooldown interval has wrong end power

### ISSUE THREAD

**Issue by hpbieker** [lcarcamo1526/TrainerRoad-to-Zwift#12]
The cooldown interval always has the same end power as the start power, but this is typically not correct.

**Comment by lcarcamo1526** [comment]
Do you have any workout name that should I look as an example?

**Comment by lcarcamo1526** [comment]
> Do you have any workout name that should I look as an example?

@hpbieker We are using a fix value for the warm-up and cooldown, if you could get me the id  _(it's usually on the workout url)_ or the name of the workout who has this behavior I could easily fix it.

**Comment by lcarcamo1526** [comment]
![Screenshot from 2022-03-14 23-53-00](https://user-images.githubusercontent.com/39929831/158309304-84c0c716-9e13-491f-acef-b563179e921d.png)
Solved in #15
