### ISSUE TITLE
NoneType Error

### ISSUE THREAD

**Issue by d3vind** [lcarcamo1526/TrainerRoad-to-Zwift#13]
![image](https://user-images.githubusercontent.com/12804992/158075267-4c40916c-91ad-4511-bfae-5c1694c5c76f.png)

**Comment by d3vind** [comment]
I can't build locally until later in the week. This may be a dos2unix issue?
Username perhaps nonetype when calling lower

**Comment by lcarcamo1526** [comment]
> I can't build locally until later in the week. This may be a dos2unix issue? Username perhaps nonetype when calling lower

Hi @d3vind, Are you running the notebook on the binder? Or locally?
Looks like it could not get the username and therefore fail to get the current training plan.
I've added some warning statements. 

Could you test the following binder and tell me if the problem persist?

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/lcarcamo1526/TrainerRoad-to-Zwift/13-nonetype-error?labpath=Trainerroad.ipynb)

Looks like trainerroad is starting to ban by IP when you run this too often.

I suggest you to run this tool locally instead on binder.

Let me know how it goes :)

**Comment by d3vind** [comment]
This issue was when running it in the binder. The username was provided so Im still not sure why the issue bubbled up. 

I just ran it locally and ended up getting a bad end point?

![image](https://user-images.githubusercontent.com/12804992/158451013-261eb679-6047-4afd-a81f-6323526c9a8b.png)

**Comment by lcarcamo1526** [comment]
> > > I can't build locally until later in the week. This may be a dos2unix issue? Username perhaps nonetype when calling lower
> > 
> > 
> > Hi @d3vind, Are you running the notebook on the binder? Or locally? Looks like it could not get the username and therefore fail to get the current training plan. I've added some warning statements.
> > Could you test the following binder and tell me if the problem persist?
> > [![Binder](https://camo.githubusercontent.com/581c077bdbc6ca6899c86d0acc6145ae85e9d80e6f805a1071793dbe48917982/68747470733a2f2f6d7962696e6465722e6f72672f62616467655f6c6f676f2e737667)](https://mybinder.org/v2/gh/lcarcamo1526/TrainerRoad-to-Zwift/13-nonetype-error?labpath=Trainerroad.ipynb)
> > Looks like trainerroad is starting to ban by IP when you run this too often.
> > I suggest you to run this tool locally instead on binder.
> > Let me know how it goes :)
> 
> I unfortunately get the same issue as the local build above

I've added a new parameter in the export training plan named,`optional_username`, you should put your username there and see how it goes (_you still have to input in the credentials in the cell before_).
I tried with yours and I got the attachment workouts.

Looks like for some reason is not passing the name thought the endpoint when connected.
![Screenshot 2022-03-16 at 13-12-45 NoneType Error · Issue #13 · lcarcamo1526 TrainerRoad-to-Zwift](https://user-images.githubusercontent.com/39929831/158659419-e1476ff7-2246-46ef-908b-d053cc6c79b6.png)
[training_plan_16_03_2022_13_15_31.zip](https://github.com/lcarcamo1526/TrainerRoad-to-Zwift/files/8268358/training_plan_16_03_2022_13_15_31.zip)

**Comment by d3vind** [comment]
I found the issue and it was a silly one, I used my password for the trainerroad forum and not the application itself. 
It seems as if it was falsely authenticating which makes sense for the noneType

**Comment by lcarcamo1526** [comment]
> It seems as if it was falsely authenticating which makes sense for the noneType

Haha, ride on!, I'm closing this issue :)
